import { generate } from "rxjs"

export const BASE_URL = 'http://103.109.7.173:7602/api/'
export const API_CONSTANT = {
    login:'Auth/Login',
    adminManufacturerList : 'Manufacturer/ManufacturerList',
    stateDropdown:'State/StateList',
    cityDropdown:'State/CityList',
    userProfileDetail:'Profile/GetUserProfileList',
    updateUser:'Profile/UpdateUserProfile',
    updateUserImage:'Profile/UpdateUserProfileImage',
    sendEmailOtp:'Profile/SendEmailOTP',
    veryEmailMobile:'Profile/VerifyEmailOTP',
    sendMobileOtp:'Profile/SendMobileOTP',
    createState:'State/AddState',
    addCity:'City/AddCityData',
    createManufacture:'Manufacturer/AddManufacturer',
    updateManufacture:'Manufacturer/UpdateManufacturer',
    distributerList:'Distributor/DistributorList',
    createDistributer:'Distributor/AddDistributor',
    updateDistributer:'Distributor/UpdateDistributor',
    certificateList :'Manufacturer/ManufacturerCertificateList',
    productList:'Product/GetProductList',
    authorityList:'Authority/GetAuthorityList',
    updateCertificate:'Manufacturer/UpdateManufacturerCertificate',
    uploadCertificate:'Manufacturer/UploadManufacturerCertificate',
    dealerList:'Dealer/GetDealerList',
    createDealer:'Dealer/AddDealer',
    updateDealer:'Dealer/UpdateDealer',
    distributerDropdown:'Common/GetDistributorListById',
    stockList : 'Device/GetVahanDeviceList',
    addSingleStock : 'Device/AddVahanDevice',
    addBulkStock : 'Device/UploadDeviceData?fk_manufacture_id=${manufactureId}&fk_device_type_id=${productId}',
    updateStock:'Device/UpdateVahanDevice',
    deviceList : 'Device/GetVahanDeviceSimStatusList',
    orderDashboard:'Request/GetRequestDashboard',
    orderProductList: 'DeviceSubCategory/GetDeviceSubCategoryList',
    stateListOnDeviceType :'Common/GetStateListOnDeviceType',
    planBasedOnState :'Common/GetPlanListBasedOnState',
    generateOrder :'Request/GenerateRequest',
    modifydevice:'Device/ModifySimInformation?iccid=${iccid}',
    managerList:'SalesManager/GetSalesManagerList',
    addManager:'SalesManager/AddSalesManager',
    updateManager:'SalesManager/UpdateSalesManager',
    salesList:'SalesManager/GetGenerateSales',
    createSales:'SalesManager/GenerateSales',
    deviceBalance:'SalesManager/CheckDeviceBalance',
    requestById : 'Request/GetRequestById',
    shippingAdderss : 'Shipping/GetShippingAddressList',
    interIntraStatus :'Request/GetInterIntraStatusById',
    deviceVahanList :"Device/GetVahanDeviceList",
    generateInvoice:'Billing/GenerateInvoice'

}
