import { generate } from "rxjs"

export const BASE_URL = 'http://103.109.7.173:7602/api/'
export const API_CONSTANT = {
    login:'Auth/Login',
    adminManufacturerList : 'Manufacturer/ManufacturerList',
    stateDropdown:'State/StateList',
    cityDropdown:'State/CityList',
    userProfileDetail:'Profile/GetUserProfileList',
    updateUser:'Profile/UpdateUserProfile',
    updateUserImage:'Profile/UpdateUserProfileImage',
    sendEmailOtp:'Profile/SendEmailOTP',
    veryEmailMobile:'Profile/VerifyEmailOTP',
    sendMobileOtp:'Profile/SendMobileOTP',
    createState:'State/AddState',
    addCity:'City/AddCityData',
    createManufacture:'Manufacturer/AddManufacturer',
    updateManufacture:'Manufacturer/UpdateManufacturer',
    distributerList:'Distributor/DistributorList',
    createDistributer:'Distributor/AddDistributor',
    updateDistributer:'Distributor/UpdateDistributor',
    certificateList :'Manufacturer/ManufacturerCertificateList',
    productList:'Product/GetProductList',
    authorityList:'Authority/GetAuthorityList',
    updateCertificate:'Manufacturer/UpdateManufacturerCertificate',
    uploadCertificate:'Manufacturer/UploadManufacturerCertificate',
    dealerList:'Dealer/GetDealerList',
    createDealer:'Dealer/AddDealer',
    updateDealer:'Dealer/UpdateDealer',
    distributerDropdown:'Common/GetDistributorListById',
    stockList : 'Device/GetVahanDeviceList',
    addSingleStock : 'Device/AddVahanDevice',
    addBulkStock : 'Device/UploadDeviceData?fk_manufacture_id=${manufactureId}&fk_device_type_id=${productId}',
    updateStock:'Device/UpdateVahanDevice',
    deviceList : 'Device/GetVahanDeviceSimStatusList',
    orderDashboard:'Request/GetRequestDashboard',
    orderProductList: 'DeviceSubCategory/GetDeviceSubCategoryList',
    stateListOnDeviceType :'Common/GetStateListOnDeviceType',
    planBasedOnState :'Common/GetPlanListBasedOnState',
    generateOrder :'Request/GenerateRequest',
    modifydevice:'Device/ModifySimInformation?iccid=${iccid}',
    managerList:'SalesManager/GetSalesManagerList',
    addManager:'SalesManager/AddSalesManager',
    updateManager:'SalesManager/UpdateSalesManager',
    salesList:'SalesManager/GetGenerateSales',
    createSales:'SalesManager/GenerateSales',
    deviceBalance:'SalesManager/CheckDeviceBalance',
    backendList:'Backend/BackendList',
    createBackend:'Backend/AddBackend',
    updateBackend:'Backend/UpdateBackend',
    stateList:'State/StateList',
    updateState:'State/UpdateState',
    cityList:'State/CityList',
    updateCity:'City/UpdateCityData',
    addProduct:'Product/AddProductData',
    updateProduct:'Product/UpdateProductData',
    rtoList:'RTO/RTOList',
    createRto:'RTO/AddRTO',
    updateRto:'RTO/UpdateRTO',
    addAuthority:'Authority/AddAuthorityData',
    updateAuthority:'Authority/UpdateAuthorityData',
    authorityPlanList:'AuthorityPlan/GetAuthorityPlanList',
    addAuthorityPlan:'AuthorityPlan/AddAuthorityPlanData',
    updateAuthorityPlan:'AuthorityPlan/UpdateAuthorityPlanData',
    categoryList:'DeviceCategory/GetDeviceCategoryList',
    createCategory:'DeviceCategory/AddDeviceCategoryData',
    updateCategory:'DeviceCategory/UpdateDeviceCategoryData',
    subCategoryList:'DeviceSubCategory/GetDeviceSubCategoryList',
    createSubCategory:'DeviceSubCategory/AddDeviceSubCategoryData',
    updateSubCategory:'DeviceSubCategory/UpdateDeviceSubCategoryData',
    gstList:'GST/GetGSTList',
    requestById : 'Request/GetRequestById',
    shippingAdderss : 'Shipping/GetShippingAddressList',
    interIntraStatus :'Request/GetInterIntraStatusById',
    deviceVahanList :"Device/GetVahanDeviceList",
    generateInvoice:'Billing/GenerateInvoice',
    shippingList :'Shipping/GetShippingAddressList',
    addShippingAddress :'Shipping/AddShippingAddress',
    updateShippingAddress :'Shipping/UpdateShippingAddress',
    deleteShippingAddress :'Shipping/DeleteShippingAddress',
    hsnList:'GST/GetGSTList',
    addHsn:'GST/CreateGST',
    updateHsn:'GST/UpdateGST',
    complainList:'Compliant/GetDeviceComplaintList',
    addComplain:'Compliant/AddDeviceComplaint',
    updateComplain:'Compliant/UpdateDeviceComplaint',
    serviceList:'Service/GetDeviceServiceList',
    createService:'Service/AddDeviceService',
    updateService:'Service/UpdateDeviceService',
    headListDD:'Support/GetSupportHeadList',
    supportList:'Support/GetSupportMemberList',
    addSupport:'Support/AddSupportMember',
    updateSupport:'Support/UpdateSupportMember',
    activationDetail:'Device/GetVahanSubInfo',
    activationList:'Device/VahanActivationRequestList',
    updateMis:'Device/vahan_update_misdetail',
    updateSim:'Device/vahan_update_simdetail',
    updateStatus:'Device/vahan_update_ar_request_status',
    certificatedata:'Device/vahan_vehicle_certificate_upload',
    deleteListData:'Device/vahan_vehicle_ar_request_delete',
    updateActivation:'Device/AddVahanSubInfo',
    vehicleType:'Device/GetVahanRegistrationTypeList',
    inventoryList:'Device/GetUserDeviceInventory',
    paymentMode:'Common/GetPaymentModeList',
    getTaxCalculation:'Request/GetTaxCalculation',
    updateRazorPaymentAsync :'Request/UpdateRazorPaymentAsync',
    itemIssue :'Billing/ItemIssue',
    orderHistory : 'Request/GetOrderRequestDetails',
    UpdateRequestOrderStatus : 'Request/UpdateRequestOrderStatus',
    paymentDetails :'Request/GetOrderPaymentDetails',
    paymentStatusList :'Common/GetPaymentStatusList',
    UpdateRequestPaymentStatus:'Request/UpdateRequestPaymentStatus',
    commonDealer : 'Common/GetDealerList',
    vahanList :'Vahan/GetVahanDataList',
    vahanSubList :'Vahan/GetVahanSubDataList',
}
